server:
  servlet:
    context-path: /demo
    session:
      timeout: 30
  port: 8081
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 30
      initial-size: 2
      max-wait: 60000
      min-idle: 2
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 30
  thymeleaf:
    prefix: classpath:/templates/
mybatis:
  mapper-locations:
  - classpath:dao/*.xml
  type-aliases-package: com.example.demo.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  
logging:
  config: classpath:logback-spring.xml